name: Fly Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:     # Run by hand

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Download and setup standalone TailwindCSS CLI
      - name: Set up TailwindCSS Standalone CLI
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.3/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss

      # Build the CSS using the standalone TailwindCSS CLI
      - name: Build CSS
        run: ./tailwindcss -i static/css/styles.css -o static/css/output.css --minify
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
